package org.devlive.sdk.openai.model;

public enum UrlModel
{
    FETCH_MODELS,
    FETCH_MODEL,
    FETCH_COMPLETIONS,
    FETCH_CHAT_COMPLETIONS,
    FETCH_USER_API_KEYS,
    FETCH_CREATE_USER_API_KEY,
    FETCH_IMAGES_GENERATIONS,
    FETCH_IMAGES_EDITS,
    FETCH_IMAGES_VARIATIONS,
    FETCH_EMBEDDINGS,
    FETCH_AUDIO_TRANSCRIPTIONS,
    FETCH_MODERATIONS,
    FETCH_EDITS,
    FETCH_FILES,
    FETCH_FINE_TUNING_JOBS,
    FETCH_FINE_TUNING_JOBS_EVENTS,
    FETCH_FINE_TUNING_JOBS_CONTENT,
    FETCH_FINE_TUNING_JOBS_CANCEL,
    FETCH_ASSISTANTS,
    FETCH_ASSISTANTS_FILES,
    FETCH_RETRIEVE_ASSISTANT,
    FETCH_RETRIEVE_ASSISTANT_FILE;
}
